//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonziRepostiory
{
    using System;
    
    public enum ConfirmStatusEnum : int
    {
        Pending = 1,
        Confirmed = 2,
        Not_Confirmed = 3,
        Admin_Confirmed = 4
    }
}
