//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonziRepostiory
{
    using System;
    
    public enum MatchingStatusEnum : int
    {
        Pending = 1,
        Matched = 2,
        Not_Matched = 3,
        Admin_Matched = 4,
        IDP = 5
    }
}
