//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonziRepostiory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matching
    {
        public int Id { get; set; }
        public Nullable<int> GHTrackId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateMatched { get; set; }
        public Nullable<int> PHTrackId { get; set; }
        public Nullable<System.DateTime> DateHelped { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public byte[] UploadedEvidence { get; set; }
    
        public virtual TrackRecord TrackRecord { get; set; }
        public virtual TrackRecord TrackRecord1 { get; set; }
    }
}
