//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonziRepostiory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matching
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateMatched { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public string UploadedEvidence { get; set; }
        public Nullable<System.DateTime> DateConfirmed { get; set; }
        public Nullable<int> MatchingStatus { get; set; }
        public Nullable<int> ConfirmationStatus { get; set; }
        public Nullable<double> Amount { get; set; }
    
        public virtual ConfirmationStatus ConfirmationStatu { get; set; }
        public virtual MatchingStatus MatchingStatu { get; set; }
        public virtual TransactionDet TransactionDet { get; set; }
    }
}
