//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonziRepostiory
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MPackage()
        {
            this.UserPackages = new HashSet<UserPackage>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<double> MinimumAmount { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<double> PercentageIncrease { get; set; }
        public Nullable<double> MaximumAmount { get; set; }
        public Nullable<int> MinimumPHDays { get; set; }
        public Nullable<int> MinimumGHDays { get; set; }
        public Nullable<int> MaximumPHDays { get; set; }
        public Nullable<int> MaximumGHDays { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPackage> UserPackages { get; set; }
    }
}
