//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonziRepostiory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NobleDBEntities : DbContext
    {
        public NobleDBEntities()
            : base("name=NobleDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Matching> Matchings { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<Tenent> Tenents { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserPackage> UserPackages { get; set; }
        public virtual DbSet<PackageSplit> PackageSplits { get; set; }
        public virtual DbSet<TransactionDetail> TransactionDetails { get; set; }
        public virtual DbSet<TransactionSplit> TransactionSplits { get; set; }
        public virtual DbSet<TrackRecord> TrackRecords { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<UserStatu> UserStatus { get; set; }
    }
}
