//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonziRepostiory
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageSplit
    {
        public int Id { get; set; }
        public string PackageDescription { get; set; }
        public Nullable<int> PackId { get; set; }
        public Nullable<int> SplitID { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public Nullable<System.DateTime> DateInitiated { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<double> Amount { get; set; }
    
        public virtual TransactionSplit TransactionSplit { get; set; }
        public virtual UserPackage UserPackage { get; set; }
    }
}
