//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonziRepostiory
{
    using System;
    
    public enum PackageStatusEnum : int
    {
        Pending = 1,
        Active = 2,
        Error = 3,
        Closed = 4,
        Matched_For_PH = 5,
        Matched_For_GH = 6
    }
}
