//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonziRepostiory
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneValidation : Verification
    {
        public string PhoneNumber { get; set; }
        public string PhoneCode { get; set; }
    }
}
