//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonziRepostiory
{
    using System;
    
    public enum RoleStatusEnum : int
    {
        Outbound_User = 1,
        General_Admin = 2,
        Super_Admin = 3,
        Promoted_Privilege = 4,
        Phone_Unconfirmed = 5,
        Success_UnConfirmed = 6,
        Disabled_User = 7
    }
}
