//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonziRepostiory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tenent()
        {
            this.TrackRecords = new HashSet<TrackRecord>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Acronyms { get; set; }
        public Nullable<bool> IsForwardFlow { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrackRecord> TrackRecords { get; set; }
    }
}
