//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonziRepostiory
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionDet()
        {
            this.Matchings = new HashSet<Matching>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> AmountIncrease { get; set; }
        public Nullable<int> MaturityTime { get; set; }
        public Nullable<int> TransactStatus { get; set; }
        public Nullable<int> TransactionAmount { get; set; }
        public Nullable<int> UserPackId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Matching> Matchings { get; set; }
        public virtual TransactionStatus TransactionStatu { get; set; }
        public virtual UserPackage UserPackage { get; set; }
    }
}
