//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonziRepostiory
{
    using System;
    
    public enum TransactionStatusEnum : int
    {
        PH_Pending = 1,
        PH_Confirmed = 2,
        PH_Provisioned = 3,
        PH_Closed = 4,
        GH_Process_Begins = 5,
        GH_Process_Completed = 6,
        GH_Process_Closed = 7,
        GH_Floating = 8,
        Disabled = 9
    }
}
