//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonziRepostiory
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionSplit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionSplit()
        {
            this.PackageSplits = new HashSet<PackageSplit>();
        }
    
        public int Id { get; set; }
        public string SplitDescription { get; set; }
        public Nullable<int> SplitPercentage { get; set; }
        public Nullable<int> TransId { get; set; }
        public Nullable<bool> IsFirst { get; set; }
        public Nullable<int> MaturityTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageSplit> PackageSplits { get; set; }
        public virtual TransactionDetail TransactionDetail { get; set; }
    }
}
