//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonziRepostiory
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserPackage()
        {
            this.TransactionDets = new HashSet<TransactionDet>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> PackId { get; set; }
        public Nullable<System.DateTime> DateStarted { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<int> PackStatus { get; set; }
        public Nullable<double> Amount { get; set; }
    
        public virtual PackageStatus PackageStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionDet> TransactionDets { get; set; }
        public virtual Registrant User { get; set; }
        public virtual Package Package { get; set; }
    }
}
