//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonziRepostiory
{
    using System;
    
    public enum ValidationStatusEnum : int
    {
        Email_Code_Generated = 1,
        Phone_Code_Generated = 2,
        Email_Verified = 3,
        Phone_Verified = 4
    }
}
