//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonziRepostiory
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Verification
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> GeneratedTime { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> DateUsed { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Status { get; set; }
        public string Remarks { get; set; }
    
        public virtual ValidationStatus ValidationStatu { get; set; }
        public virtual User User { get; set; }
    }
}
